### PR TITLE
Prevent suspended user from contributing to spawns

### PR DESCRIPTION
**Pull request by WitherredAway**
This commit makes it so that suspended users' messages do not contribute to spawns. This is an important change in order to prevent autospammers from still working after suspension (which defeats the purpose of suspending autospammers)

### CODE REVIEW

**Comment by Neelesh01928373829** [comment]
Hi sir
My self neelesh.
My account got suspended for cross trading. I don't know about that before . I am sorry for that and i will take care so I don't repeat that mistake again . Pls it's my humble request to u to pls unsuspend my account plz .
I will take care about it . 
I have submitted bot suspension  letter but it's long time i don't got any reply . Pls unsuspend my account 

Discord name Neelesh#2749

**Comment by WitherredAway** [comment]
@Neelesh01928373829 Please open a ticket for your suspension at https://discord.gg/poketwo-support and we'll help sort things out. This place unfortunately isn't meant for such discussions

**Comment by pikaninja** [comment]
fetch_member_info is already fetched in the `increase_xp` message, mmight as well refactor that along with this to allow for only one call to the database

**Comment by WitherredAway** [comment]
That's a good point! I did think about that but i did not want to mess with anything else since I'm not sure if the `increase_xp` method was used anywhere else and if it would mess anything up

**Comment by pikaninja** [comment]
As far as i know, it doesnt, you could search through the code to make sure if you want(This code was originally just in the `on_message` method, i was actually the one who moved it to a new method. At that point there was definitely no mentions of it elsewhere, i'm not sure if oliver has added or changed anything in the year after that, would be good to check)

**Comment by WitherredAway** [comment]
Okay, will do when i can. Thank you :)

**Comment by WitherredAway** [comment]
Is this okay? @pikaninja

**Comment by pikaninja** [comment]
This is mostly fine, i would move the `ctx.valid` up though, as theres no point to fetch the member if its a valid command

**Comment by WitherredAway** [comment]
Oo that makes sense, thank you

**Pull request closed without merging**
