### PR TITLE
Increase shiny rates for keelay#3500 because I have been having a hard time catching shinies

### PR DESCRIPTION
**Pull request by kyle-he**
I've been playing for a long time and I haven't caught a shiny, so this update will help fix this issue!

### CODE REVIEW

**Review by person583375239 — CHANGES_REQUESTED** [review]
Changes required:
Fix to my discord id instead please

**Comment by kyle-he** [comment]
Sounds good, here are the users currently in the list:
keelay#3500
sunflora#0159

Please approve or comment on this pull request to be added.

**Review by person583375239 — APPROVED** [review]

**Review by michaelsong4399 — CHANGES_REQUESTED** [review]
I think it would be a good idea to also include user 756135959145218128 for reason "special."

**Comment by Kuraven** [comment]
> Sounds good, here are the users currently in the list:
> keelay#3500
> sunflora#159
> 
> Please approve or comment on this pull request to be added.

count me in

**Comment by NearWillHackYou** [comment]
it ain't about how hard you try, it's just luck and ya'll chances of shiny is probably below 0

**Comment by Kuraven** [comment]
> it ain't about how hard you try, it's just luck and ya'll chances of shiny is probably below 0

ban this man from the list keelay

**Comment by NearWillHackYou** [comment]
imagine thinking you'll get shiny boost lmao

**Comment by Hyperbub** [comment]
So far, the poketwo team can support the shiny boosting of the following player(s):

Sunflora#0159 (643697069596606475)
Sunflora#0159 (643697069596606475)
Sunflora#0159 (643697069596606475)
Sunflora#0159 (643697069596606475)

We will no longer be accepting suggestions for players to have boosted shiny rates.
Thank you for your patience and understanding.

**Comment by kyle-he** [comment]
Thank you everyone for your thoughts, and after much consideration, I have decided to remove everyone except for myself from the list to prevent keep the pull request consistent with the title. 

I will now be approving and merging with master. If you would like to have a boost of your very own, I suggest you start your own pull request. Thank you.

**Review by RedVertigoFox — COMMENTED** [review]
this is amazing

**Pull request merged**
