### PR TITLE
Update trading.py

### PR DESCRIPTION
**Pull request by IamEinstein**
Solution to issue #105

### CODE REVIEW

**Comment by oliver-ni** [comment]
hi! thanks for the contribution, but I won't merge this as-is because of all the random changes. I think your autoformatter is messing with the code.

Can you please restore back everything else and only commit the relevant change?

**Review by oliver-ni — CHANGES_REQUESTED** [review]
^

**Comment by IamEinstein** [comment]
Hi, as you had asked, I've removed the formatting from the file

**Comment by oliver-ni** [comment]
Thank you!

**Comment by IamEinstein** [comment]
Welcome
😃

**Pull request merged**
