### PR TITLE
Remove ! as it looks weird next to the mention in pokemon catch message

### PR DESCRIPTION
**Pull request by CreeperPlanet26**

### CODE REVIEW

**Comment by person583375239** [comment]
Which exclamation mark are you talking about? Perhaps add a screenshot

**Comment by CreeperPlanet26** [comment]
image

**Comment by person583375239** [comment]
If the ! does get removed after the users name, it should have a full stop there instead, not _nothing_

**Comment by CreeperPlanet26** [comment]
I put the `!` back but I changed it so that it doesn't mention the user as that might fill up their notis

**Comment by person583375239** [comment]
It's needed to make it obvious who caught it too (if multiple people are trying)

**Comment by CreeperPlanet26** [comment]
I guess but it would fill it up in inbox section. I guess i will take out the ! because the Discord UI has very little margin between the mention and the !

**Comment by CreeperPlanet26** [comment]
Is this what you mean by full stop?

**Comment by oliver-ni** [comment]
I don't believe this change is necessary, it looks fine IMO

**Pull request closed without merging**
