### PR TITLE
Add mp aliases on marketplace command

### PR DESCRIPTION
**Pull request by davidcanas**
Many people use p!mp to use p!marketplace but there is no such aliase.

### CODE REVIEW

**Comment by ImSalad** [comment]
Can I get a cheese Borger

**Comment by WitherredAway** [comment]
Here 🍔
Now please refrain from posting unrelated comments here

**Comment by ImSalad** [comment]
Can I get a chiken wings on the side with special request ( torchic meat pls)

**Comment by davidcanas** [comment]
What the heck ?
are you drunk?

**Comment by ImSalad** [comment]
O.o

**Pull request closed without merging**
